# Generated by Django 4.2.7 on 2023-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_Notes', '0003_alter_note_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='add_to_do',
            field=models.BooleanField(default=True),
        ),
    ]
