# Generated by Django 4.1.7 on 2023-11-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_Email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='_from',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='_subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='_to',
            new_name='to',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='_user',
            new_name='user',
        ),
    ]
