# Generated by Django 4.2.7 on 2023-11-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_Email', '0002_rename__from_email_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='last_synched',
            new_name='dateReceived',
        ),
    ]
