# Generated by Django 4.2.7 on 2023-11-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Email', '0004_alter_email_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='dateReceived',
            field=models.DateTimeField(),
        ),
    ]
