# Generated by Django 4.2.7 on 2023-11-23 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('C_Client', '0002_rename_email_client_eml'),
        ('A_Email', '0005_alter_email_datereceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='clt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='C_Client.client'),
        ),
        migrations.AddField(
            model_name='email',
            name='todo',
            field=models.BooleanField(default=False),
        ),
    ]
