# Generated by Django 4.1.7 on 2023-11-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imap_port',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='smtp_port',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smtp_server',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
